apiVersion: v1
kind: Service
metadata:
  name: otp-apis-service
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32020
  type: NodePort
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: otp-apis-url
  namespace: default
spec:
  path: /
  to:
    kind: Service
    name: otp-apis-service
  port:
    targetPort: 8080
